---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
  - type: document
    label: Help
    path: README.md
    read_only: true
  - type: document
    path: source/_data/global.yml
    label: Global
  - type: heading
    label: Content
  - type: directory
    path: source/posts
    label: Posts
    create: documents
    match: '*.md'
    templates:
      - post
  - type: directory
    label: Data
    path: source/_data
    match: '*.toml'
    new_doc_ext: '.toml'
    create: all
  - type: directory
    path: _pages
    label: Pages
    create: documents
    match: '*'
upload_dir: uploads
public_path: '/uploads'
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
build:
  preview_env:
    - ELEVENTY_ENV=staging
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: '/srv'
  working_dir: '/srv'
  instant_preview_command: npm run forestry:preview
