---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: source/_data/home.yml
  label: Home
  match: "**/*"
- type: heading
  label: Content
- type: directory
  path: source/posts
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: _pages
  label: Pages
  create: documents
  match: "*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - ELEVENTY_ENV=staging
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
